### PR TITLE
Upstream tandem profile generation

### PR DESCRIPTION
**Pull request by LeopoldKellers**
I just tested the code I wrote and it spits the correct profile into the sedworkdir.

Don't pull this before merging the template's tandem branch, since it will produce garbage otherwise. Until then, the special profile from yesterday's commit suffices from my point of view.

Is there anything left to be done? Otherwise I'd consider the tandem story finished for the moment.

### CODE REVIEW

**Comment by poutnikl** [comment]
Looks fine. I will merge as suggested, after merging tandem to master branch of Trekking-Poutnik rep.

**Comment by poutnikl** [comment]
Note that I recommend @LeopoldKellers a personal version of sedbatch.bat, generating tandem versions of all relevant bike profiles. It may be handy not to be limited to the profile based on the intact template, i.e. Trekking-Dry.

**Comment by poutnikl** [comment]
Tandem branch has been merged to master in Trekking-Poutnik rep. Now the develop branch is about to be merged to create RC for new release.

**Comment by poutnikl** [comment]
@LeopoldKellers 2 tandem profile generation is included in Linux/Android termux script Sedbatch in Brouter-profiles. (Windows sedbatch batch is foe now little outdated.)

**Comment by poutnikl** [comment]
@LeopoldKellers  I will include the tandem profile generation to windows sedbatch.bat as well, aside of updating it.
I will close this pull request as I will not perform an automatic merge. the important things is the tandem profile is included in the current master + develop templates, plus generation will be present in the batches.

**Comment by LeopoldKellers** [comment]
Pretty cool, thank you!
Looking forward to trying it out in v2.7 soon :-)

**Pull request closed without merging**
